export const AUTH = "AUTH";
export const ALERT = "ALERT";
export const USER = {
  CREATE_USER: "CREATE_USER",
  GET_ALL_USER: "GET_ALL_USER",
  GET_USER_BY_ROLE: "GET_USER_BY_ROLE",
  DELETE_USER_BY_ID: "DELETE_USER_BY_ID",
};
export const PRODUCT_LINE = {
  CREATE_PRODUCT_LINE: "CREATE_PRODUCT_LINE",
  GET_ALL_PRODUCT_LINE: "GET_ALL_PRODUCT_LINE",
  DELETE_PRODUCT_LINE: "DELETE_PRODUCT_LINE",
};

export const WAREHOUSE = {
  CREATE_WAREHOUSE: "CREATE_WAREHOUSE",
  GET_ALL_WAREHOUSE: "GET_ALL_WAREHOUSE",
  DELETE_WAREHOUSE: "DELETE_WAREHOUSE",
  GET_ALL_OWN_WAREHOUSE: "GET_ALL_OWN_WAREHOUSE",
};
